# Generated by Django 4.0.5 on 2022-07-05 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_about_category_img_category_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='about',
        ),
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
        migrations.RemoveField(
            model_name='category',
            name='price',
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Bag name')),
                ('img', models.ImageField(null=True, upload_to='media', verbose_name='Bag image')),
                ('about', models.TextField(null=True, verbose_name='Bag about')),
                ('price', models.IntegerField(null=True, verbose_name='Bag price')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bagcat', to='main.category')),
            ],
            options={
                'verbose_name': 'Bag',
                'verbose_name_plural': 'Bags',
            },
        ),
    ]
